Dummybranch
miraclineA/online-Shopping pull request #1
Opened 2022-12-08 13:18 UTC by miraclineA

2022-12-08 14:51 UTC, Sushmitha-Vk requested changes

2022-12-08 14:51 UTC, Sushmitha-Vk commented on src/app/header/header.component.html
> +<!-- <a mat-list-item appHiglightdirective background="rgb(227, 157, 214)" routerLink="/goshopping" (click)="snav.toggle()" >Go To Shopping</a>  -->
remove commented code

2022-12-13 06:24 UTC, Sushmitha-Vk approved these changes

2022-12-13 06:35 UTC, miraclineA commented on src/app/header/header.component.html
> +<!-- <a mat-list-item appHiglightdirective background="rgb(227, 157, 214)" routerLink="/goshopping" (click)="snav.toggle()" >Go To Shopping</a>  -->
resolved

2022-12-13 06:59 UTC, merged