interface changes
miraclineA/online-Shopping pull request #2
Opened 2022-12-13 07:59 UTC by miraclineA

2022-12-13 12:43 UTC, Sushmitha-Vk requested changes

2022-12-13 12:43 UTC, Sushmitha-Vk commented on src/app/service-example.service.ts
>        console.log('----val',val)
remove console

2022-12-13 16:50 UTC, miraclineA commented on src/app/service-example.service.ts
>        console.log('----val',val)
resolved

2022-12-14 05:26 UTC, Sushmitha-Vk approved these changes

2022-12-14 05:32 UTC, merged